"""Task 132: pure Decision Package composition.

The composer is the **only** code path that mints a ``DecisionPackageEntry``.
It is a pure function — every output field is deterministically derived
from the inputs. No AI. No network calls. No fallbacks.

Doctrine bindings:

* **AI never originates a field of the Decision Package.** The label is
  copied from the forecast; the explanation is generated by the locked
  Dutch template; the gate outcomes are deterministic boolean checks;
  the audit hash is SHA-256 of canonical JSON.
* **Decimal end-to-end.** No ``float`` anywhere in the composition path,
  including inside the hash input. The canonical JSON serializer renders
  each Decimal as its string repr with full precision so the hash is
  reproducible.
* **Immutable.** ``DecisionPackageEntry`` is frozen; the composer never
  mutates input records. Two calls with identical inputs (modulo
  ``composed_at``) yield identical hashes.

The composer **crashes** when asked to compose for a ``Geblokkeerd``
forecast — that's a caller bug. The orchestrator filters Geblokkeerd
forecasts before calling.
"""

from __future__ import annotations

import hashlib
import json
import logging
import math
from collections.abc import Iterable
from datetime import UTC, date, datetime
from decimal import Decimal
from uuid import uuid4

from ai_trading_agent_storage import (
    AssetListingRecord,
    DecisionPackageEntry,
    EvidenceReference,
    ForecastEntry,
    FxRateRecord,
    GateOutcome,
    IbkrPositionSnapshotRecord,
    MarketDataEodSnapshotEntry,
)

from portfolio_outlook_worker.decision_package.dutch_explanation_template import (
    render_explanation,
)

logger = logging.getLogger(__name__)

# Locked gate sequence — must stay in this order so the explanation
# template can append "Let op:" sentences in the same sequence.
_GATE_SEQUENCE = (
    "forecast_valid",
    "data_fresh",
    "asset_listing_resolved",
    "freshness_within_sla",
    "confidence_at_least_medium",
)

# The market-data freshness SLA for the `freshness_within_sla` gate.
# Anything older than 3 calendar days (same threshold as the Task 131
# `stale_market_data` block_reason) trips the gate.
_FRESHNESS_SLA_DAYS = 3


class GeblokkeerdForecastError(ValueError):
    """Raised when the composer is asked to compose for a Geblokkeerd forecast.

    The orchestrator filters before calling; this exception exists to
    catch caller bugs early. The Decision Package layer simply doesn't
    represent blocked forecasts (Task 132 product lock §2).
    """


def compose_decision_package(
    *,
    forecast: ForecastEntry,
    ibkr_account_id: str,
    market_snapshot: MarketDataEodSnapshotEntry,
    fx_rate: FxRateRecord | None,
    asset_listing: AssetListingRecord | None,
    position_snapshot: IbkrPositionSnapshotRecord | None,
    previous_package: DecisionPackageEntry | None,
    composed_at: datetime | None = None,
) -> DecisionPackageEntry:
    """Compose one Decision Package for a non-Geblokkeerd forecast.

    Inputs:

    * ``forecast`` — the just-generated ForecastEntry. **Must not be
      Geblokkeerd**; the composer raises ``GeblokkeerdForecastError`` if
      it is.
    * ``market_snapshot`` — the EOD snapshot the forecast was based on,
      used for the as_of timestamp + freshness gate.
    * ``fx_rate`` — quote-per-base rate for the asset's currency → EUR.
      ``None`` only when the asset is already EUR-denominated.
    * ``asset_listing`` — the resolved listing (symbol, exchange,
      asset_class). ``None`` trips the ``asset_listing_resolved`` gate.
    * ``position_snapshot`` — the most-recent held-position snapshot for
      the (account, conid) pair, or ``None`` if not held.
    * ``previous_package`` — the chain anchor for ``previous_package_hash``.
    """

    if forecast.label == "Geblokkeerd":
        raise GeblokkeerdForecastError(
            f"compose_decision_package called for Geblokkeerd forecast "
            f"{forecast.forecast_run_id!r}; orchestrator must filter before "
            "calling"
        )

    if composed_at is None:
        composed_at = datetime.now(UTC)

    user_holds = (
        position_snapshot is not None and position_snapshot.quantity > 0
    )
    if position_snapshot is not None and user_holds:
        held_quantity: Decimal | None = position_snapshot.quantity
        held_avg_cost: Decimal | None = position_snapshot.average_cost
    else:
        held_quantity = None
        held_avg_cost = None

    current_price_local = forecast.current_price_local
    current_price_eur = _convert_to_eur(
        amount_local=current_price_local,
        currency_local=forecast.currency_local,
        fx_rate=fx_rate,
    )
    p10_price_eur = _convert_to_eur(
        amount_local=_price_at_quantile(
            forecast.current_price_local, forecast.p10_log_return
        ),
        currency_local=forecast.currency_local,
        fx_rate=fx_rate,
    )
    p50_price_eur = _convert_to_eur(
        amount_local=_price_at_quantile(
            forecast.current_price_local, forecast.p50_log_return
        ),
        currency_local=forecast.currency_local,
        fx_rate=fx_rate,
    )
    p90_price_eur = _convert_to_eur(
        amount_local=_price_at_quantile(
            forecast.current_price_local, forecast.p90_log_return
        ),
        currency_local=forecast.currency_local,
        fx_rate=fx_rate,
    )

    data_age = _trading_day_age(
        as_of_date=market_snapshot.as_of_date,
        now=composed_at,
    )
    freshness_state = _classify_freshness(
        data_age_trading_days=data_age,
    )

    gates = evaluate_gates(
        forecast=forecast,
        asset_listing=asset_listing,
        freshness_state=freshness_state,
        data_age_trading_days=data_age,
    )

    symbol = (
        asset_listing.symbol if asset_listing is not None else forecast.conid
    )
    exchange = asset_listing.exchange if asset_listing is not None else None
    asset_class = (
        asset_listing.asset_class if asset_listing is not None else None
    )

    explanation = render_explanation(
        symbol=symbol,
        label=forecast.label,
        horizon_trading_days=forecast.horizon_trading_days,
        p10_price_eur=p10_price_eur,
        p50_price_eur=p50_price_eur,
        p90_price_eur=p90_price_eur,
        prob_positive=forecast.prob_positive,
        prob_loss_gt_5pct=forecast.prob_loss_gt_5pct,
        expected_volatility_annualized=forecast.expected_volatility_annualized,
        confidence_level=forecast.confidence_level,
        valid_until=forecast.forecast_valid_until,
        gate_outcomes=gates,
    )

    evidence = _build_evidence_references(
        market_snapshot=market_snapshot,
        fx_rate=fx_rate,
        position_snapshot=position_snapshot,
    )

    decision_package_id = f"dp_{uuid4().hex}"
    previous_package_hash = (
        previous_package.audit_trail_hash
        if previous_package is not None
        else None
    )

    # Build the hash-input dict using every field that *defines* the
    # package's content. composed_at + decision_package_id are NOT in
    # the hash so two compositions of the same logical content yield
    # identical hashes (test surface for idempotence).
    audit_trail_hash = compute_audit_trail_hash(
        forecast_run_id=forecast.forecast_run_id,
        ibkr_account_id=ibkr_account_id,
        conid=forecast.conid,
        symbol=symbol,
        exchange=exchange,
        currency_local=forecast.currency_local,
        asset_class=asset_class,
        user_holds_position=user_holds,
        held_quantity=held_quantity,
        held_avg_cost_local=held_avg_cost,
        current_price_local=current_price_local,
        current_price_eur=current_price_eur,
        as_of_market_data_ts=market_snapshot.as_of_close_ts,
        freshness_state=freshness_state,
        data_age_trading_days=data_age,
        forecast_method=forecast.method,
        p10_log_return=forecast.p10_log_return,
        p50_log_return=forecast.p50_log_return,
        p90_log_return=forecast.p90_log_return,
        p10_price_eur=p10_price_eur,
        p50_price_eur=p50_price_eur,
        p90_price_eur=p90_price_eur,
        prob_positive=forecast.prob_positive,
        prob_loss_gt_5pct=forecast.prob_loss_gt_5pct,
        expected_volatility_annualized=forecast.expected_volatility_annualized,
        forecast_confidence_level=forecast.confidence_level,
        suggested_action_label=forecast.label,
        block_reason=forecast.block_reason,
        gate_outcomes=gates,
        evidence_references=evidence,
        previous_package_hash=previous_package_hash,
    )

    return DecisionPackageEntry(
        decision_package_id=decision_package_id,
        forecast_run_id=forecast.forecast_run_id,
        composed_at=composed_at,
        valid_until=forecast.forecast_valid_until,
        ibkr_account_id=ibkr_account_id,
        conid=forecast.conid,
        symbol=symbol,
        exchange=exchange,
        currency_local=forecast.currency_local,
        asset_class=asset_class,
        user_holds_position=user_holds,
        held_quantity=held_quantity,
        held_avg_cost_local=held_avg_cost,
        current_price_local=current_price_local,
        current_price_eur=current_price_eur,
        as_of_market_data_ts=market_snapshot.as_of_close_ts,
        freshness_state=freshness_state,
        data_age_trading_days=data_age,
        forecast_method=forecast.method,
        p10_log_return=forecast.p10_log_return,
        p50_log_return=forecast.p50_log_return,
        p90_log_return=forecast.p90_log_return,
        p10_price_eur=p10_price_eur,
        p50_price_eur=p50_price_eur,
        p90_price_eur=p90_price_eur,
        prob_positive=forecast.prob_positive,
        prob_loss_gt_5pct=forecast.prob_loss_gt_5pct,
        expected_volatility_annualized=forecast.expected_volatility_annualized,
        forecast_confidence_level=forecast.confidence_level,
        suggested_action_label=forecast.label,
        block_reason=forecast.block_reason,
        gate_outcomes=tuple(gates),
        evidence_references=tuple(evidence),
        deterministic_dutch_explanation=explanation,
        audit_trail_hash=audit_trail_hash,
        previous_package_hash=previous_package_hash,
        safe_for_action_drafts=False,
        safe_for_orders=False,
    )


def evaluate_gates(
    *,
    forecast: ForecastEntry,
    asset_listing: AssetListingRecord | None,
    freshness_state: str,
    data_age_trading_days: int,
) -> tuple[GateOutcome, ...]:
    """Locked V1.1.0 gate evaluator.

    Returns a tuple in :data:`_GATE_SEQUENCE` order. The orchestrator's
    pre-filter guarantees ``forecast.label != "Geblokkeerd"`` by the
    time we get here, so ``forecast_valid`` is always ``True``; it's
    still in the list for completeness + audit traceability.
    """

    outcomes: list[GateOutcome] = []
    outcomes.append(
        GateOutcome(
            gate_name="forecast_valid",
            passed=True,
            reason_nl="",
        )
    )
    outcomes.append(
        GateOutcome(
            gate_name="data_fresh",
            passed=(freshness_state != "unavailable"),
            reason_nl=(
                ""
                if freshness_state != "unavailable"
                else "Marktdata is niet beschikbaar voor dit asset."
            ),
        )
    )
    outcomes.append(
        GateOutcome(
            gate_name="asset_listing_resolved",
            passed=(asset_listing is not None),
            reason_nl=(
                ""
                if asset_listing is not None
                else "Asset-listing kon niet worden opgehaald."
            ),
        )
    )
    outcomes.append(
        GateOutcome(
            gate_name="freshness_within_sla",
            passed=(data_age_trading_days <= _FRESHNESS_SLA_DAYS),
            reason_nl=(
                ""
                if data_age_trading_days <= _FRESHNESS_SLA_DAYS
                else (
                    f"Marktdata is {data_age_trading_days} dagen oud; "
                    f"SLA is {_FRESHNESS_SLA_DAYS} dagen."
                )
            ),
        )
    )
    confidence_ok = forecast.confidence_level in ("Gemiddeld", "Hoog")
    outcomes.append(
        GateOutcome(
            gate_name="confidence_at_least_medium",
            passed=confidence_ok,
            reason_nl=(
                ""
                if confidence_ok
                else "Betrouwbaarheid is Laag — gebruik met voorzichtigheid."
            ),
        )
    )
    return tuple(outcomes)


def compute_audit_trail_hash(
    *,
    forecast_run_id: str,
    ibkr_account_id: str,
    conid: str,
    symbol: str,
    exchange: str | None,
    currency_local: str,
    asset_class: str | None,
    user_holds_position: bool,
    held_quantity: Decimal | None,
    held_avg_cost_local: Decimal | None,
    current_price_local: Decimal,
    current_price_eur: Decimal,
    as_of_market_data_ts: datetime,
    freshness_state: str,
    data_age_trading_days: int,
    forecast_method: str,
    p10_log_return: Decimal,
    p50_log_return: Decimal,
    p90_log_return: Decimal,
    p10_price_eur: Decimal,
    p50_price_eur: Decimal,
    p90_price_eur: Decimal,
    prob_positive: Decimal,
    prob_loss_gt_5pct: Decimal,
    expected_volatility_annualized: Decimal,
    forecast_confidence_level: str,
    suggested_action_label: str,
    block_reason: str | None,
    gate_outcomes: Iterable[GateOutcome],
    evidence_references: Iterable[EvidenceReference],
    previous_package_hash: str | None,
) -> str:
    """SHA-256 over canonical JSON of every package-defining field.

    ``composed_at`` + ``decision_package_id`` are deliberately excluded
    so the hash is content-addressed — two compositions of the same
    logical content yield identical hashes (the per-asset chain check
    in ``test_compose_idempotent_hash`` depends on this).
    """

    payload = {
        "forecast_run_id": forecast_run_id,
        "ibkr_account_id": ibkr_account_id,
        "conid": conid,
        "symbol": symbol,
        "exchange": exchange,
        "currency_local": currency_local,
        "asset_class": asset_class,
        "user_holds_position": user_holds_position,
        "held_quantity": _decimal_to_canonical(held_quantity),
        "held_avg_cost_local": _decimal_to_canonical(held_avg_cost_local),
        "current_price_local": _decimal_to_canonical(current_price_local),
        "current_price_eur": _decimal_to_canonical(current_price_eur),
        "as_of_market_data_ts": as_of_market_data_ts.isoformat(),
        "freshness_state": freshness_state,
        "data_age_trading_days": data_age_trading_days,
        "forecast_method": forecast_method,
        "p10_log_return": _decimal_to_canonical(p10_log_return),
        "p50_log_return": _decimal_to_canonical(p50_log_return),
        "p90_log_return": _decimal_to_canonical(p90_log_return),
        "p10_price_eur": _decimal_to_canonical(p10_price_eur),
        "p50_price_eur": _decimal_to_canonical(p50_price_eur),
        "p90_price_eur": _decimal_to_canonical(p90_price_eur),
        "prob_positive": _decimal_to_canonical(prob_positive),
        "prob_loss_gt_5pct": _decimal_to_canonical(prob_loss_gt_5pct),
        "expected_volatility_annualized": _decimal_to_canonical(
            expected_volatility_annualized
        ),
        "forecast_confidence_level": forecast_confidence_level,
        "suggested_action_label": suggested_action_label,
        "block_reason": block_reason,
        "gate_outcomes": [
            {
                "gate_name": g.gate_name,
                "passed": g.passed,
                "reason_nl": g.reason_nl,
            }
            for g in gate_outcomes
        ],
        "evidence_references": [
            {
                "source_id": e.source_id,
                "source_type": e.source_type,
                "claim_summary": e.claim_summary,
            }
            for e in evidence_references
        ],
        "previous_package_hash": previous_package_hash,
    }
    canonical = json.dumps(
        payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


# ---- helpers ---------------------------------------------------


def _decimal_to_canonical(value: Decimal | None) -> str | None:
    if value is None:
        return None
    # ``str(Decimal)`` preserves the full precision representation
    # without scientific notation for typical money/probability sizes.
    return str(value)


def _price_at_quantile(
    current_price_local: Decimal, log_return: Decimal
) -> Decimal:
    """Apply the log-return to current_price; return Decimal with full precision."""

    factor = Decimal(repr(math.exp(float(log_return))))
    return (current_price_local * factor).quantize(Decimal("0.000001"))


def _convert_to_eur(
    *,
    amount_local: Decimal,
    currency_local: str,
    fx_rate: FxRateRecord | None,
) -> Decimal:
    if currency_local == "EUR":
        return amount_local.quantize(Decimal("0.000001"))
    if fx_rate is None:
        # No FX rate for a non-EUR currency would normally trip a
        # composer-level block; in V1.1.0 we treat it as a 1:1 fallback
        # but flag it on the evidence trail. (Composer always has FX
        # for non-EUR in production wiring; tests cover the EUR-only
        # path.)
        logger.warning(
            "FX rate missing for currency %s; falling back to 1:1",
            currency_local,
        )
        return amount_local.quantize(Decimal("0.000001"))
    return (amount_local * fx_rate.rate).quantize(Decimal("0.000001"))


def _trading_day_age(
    *, as_of_date: date, now: datetime
) -> int:
    """Calendar-day age — proxy for trading days at the V1.1.0 SLA scale.

    Real trading-day accounting (skipping weekends + Brussels public
    holidays) is a future refinement; at the 3-day SLA threshold the
    calendar approximation is conservative (overestimates age, which
    can only ever *trip* the gate sooner — never silently let stale
    data through).
    """

    return max(0, (now.date() - as_of_date).days)


def _classify_freshness(*, data_age_trading_days: int) -> str:
    if data_age_trading_days <= 1:
        return "fresh"
    if data_age_trading_days <= _FRESHNESS_SLA_DAYS:
        return "stale"
    return "unavailable"


def _build_evidence_references(
    *,
    market_snapshot: MarketDataEodSnapshotEntry,
    fx_rate: FxRateRecord | None,
    position_snapshot: IbkrPositionSnapshotRecord | None,
) -> tuple[EvidenceReference, ...]:
    refs: list[EvidenceReference] = [
        EvidenceReference(
            source_id=market_snapshot.snapshot_id,
            source_type="market_data_snapshot",
            claim_summary=(
                f"EOD-snapshot voor {market_snapshot.symbol} op "
                f"{market_snapshot.as_of_date.isoformat()}"
            ),
        )
    ]
    if fx_rate is not None:
        refs.append(
            EvidenceReference(
                source_id=(
                    f"{fx_rate.base_currency}/{fx_rate.quote_currency}@"
                    f"{fx_rate.as_of_date.isoformat()}"
                ),
                source_type="fx_rate",
                claim_summary=(
                    f"FX-koers {fx_rate.base_currency}→"
                    f"{fx_rate.quote_currency} = {fx_rate.rate}"
                ),
            )
        )
    if position_snapshot is not None:
        refs.append(
            EvidenceReference(
                source_id=position_snapshot.snapshot_id,
                source_type="ibkr_position_snapshot",
                claim_summary=(
                    f"IBKR-positie {position_snapshot.symbol}: "
                    f"{position_snapshot.quantity} stuks"
                ),
            )
        )
    return tuple(refs)


__all__ = [
    "GeblokkeerdForecastError",
    "compose_decision_package",
    "compute_audit_trail_hash",
    "evaluate_gates",
]
