"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { apiClient, type FreshnessAuditResponse } from "@/lib/apiClient";
import { booleanBlockedLabel, formatDateTime } from "../../auditFormatting";

type FreshnessDetail = FreshnessAuditResponse & { linked_readiness_evaluation_id?: string | null; linked_request_log_id?: string | null };
export default function Page() {
  const params = useParams<{ freshnessAuditId: string }>(); const [record, setRecord] = useState<FreshnessDetail | null>(null); useEffect(() => { void (async () => { const result = await apiClient.getRequestAuditFreshnessAudit(params.freshnessAuditId); if (result.ok) setRecord(result.data as FreshnessDetail); })(); }, [params.freshnessAuditId]); if (!record) return <main className="page-wrap"><p className="empty-state">Laden, niet gevonden of API niet bereikbaar.</p></main>; const linkedRequestId = record.linked_request_log_id ?? record.request_log_id; return <main className="page-wrap"><h2>Freshness-audit detail</h2><p className="audit-help">Freshness is audit/status-only. Dit unlockt geen analyse, suggesties, actiedrafts, Decision Packages of orders.</p><section className="dashboard-card audit-detail-card"><div className="audit-field-grid"><p><b>ID</b><br/>{record.freshness_audit_id}</p><p><b>Geëvalueerd</b><br/>{formatDateTime(record.evaluated_at)}</p><p><b>Domein</b><br/>{record.data_domain}</p><p><b>Status</b><br/>{record.freshness_status}</p><p><b>Reason code</b><br/>{record.reason_code ?? "-"}</p><p><b>Source timestamp</b><br/>{formatDateTime(record.source_timestamp)}</p><p><b>Observed age</b><br/>{record.observed_age_seconds ?? "-"}</p><p><b>Expected max age</b><br/>{record.expected_max_age_seconds ?? "-"}</p><p><b>Expires</b><br/>{formatDateTime(record.expires_at)}</p><p><b>safe_for_analysis</b><br/>{booleanBlockedLabel(record.safe_for_analysis)}</p><p><b>safe_for_suggestions</b><br/>{booleanBlockedLabel(record.safe_for_suggestions)}</p><p><b>safe_for_action_drafts</b><br/>{booleanBlockedLabel(record.safe_for_action_drafts)}</p></div><div className="cross-link-block"><p>{linkedRequestId ? <Link href={`/audit/request-logs/${linkedRequestId}`}>Open gelinkte request-log</Link> : "Geen request-link"}</p><p>Readiness evaluatie: {record.linked_readiness_evaluation_id ?? "-"}</p></div></section></main>; }
